config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'front_pages#home'

  get 'dashboard', to: 'dashboard#index', as: :dashboard

  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  get   'password_reset',     to: 'password_resets#new',            as: :password_reset
  post  'password_reset',     to: 'password_resets#create'
  get   'reset_token',        to: 'password_resets#enter_token',           as: :password_reset_token
  get   'reset_token/:token', to: 'password_resets#submit_token_from_email', as: :password_reset_token_from_email
  post  'reset_token',        to: 'password_resets#submit_token'
  patch 'password_reset',     to: 'password_resets#reset_password'

  resources :clients
  resources :projects
  resources :grades
  resources :roles
  resources :skills
  resources :staff_resources
  resources :engagements
  resources :users

  namespace :wrap do
    get 'charts/c3', to: 'charts#c3', as: :charts_c3
    get 'charts/chartist', to: 'charts#chartist', as: :charts_chartist
    get 'charts/chartjs', to: 'charts#chartjs', as: :charts_chartjs
    get 'charts/flot', to: 'charts#flot', as: :charts_flot
    get 'charts/gmaps', to: 'charts#gmaps', as: :charts_gmaps
    get 'charts/mapael', to: 'charts#mapael', as: :charts_mapael
    get 'charts/morrisjs', to: 'charts#morrisjs', as: :charts_morrisjs
    get 'charts/sparkline', to: 'charts#sparkline', as: :charts_sparkline
    get 'dashboards/dashboard-2', to: 'dashboards#dashboard_2', as: :dashboards_dashboard_2
    get 'dashboards/dashboard-3', to: 'dashboards#dashboard_3', as: :dashboards_dashboard_3
    get 'dashboards/dashboard-4', to: 'dashboards#dashboard_4', as: :dashboards_dashboard_4
    get 'dashboards/dashboard-5', to: 'dashboards#dashboard_5', as: :dashboards_dashboard_5
    get 'forms/controls', to: 'forms#controls', as: :forms_controls
    get 'forms/custom-controls', to: 'forms#custom_controls', as: :forms_custom_controls
    get 'forms/dual-listbox', to: 'forms#dual_listbox', as: :forms_dual_listbox
    get 'forms/editors', to: 'forms#editors', as: :forms_editors
    get 'forms/extras', to: 'forms#extras', as: :forms_extras
    get 'forms/file-upload', to: 'forms#file_upload', as: :forms_file_upload
    get 'forms/input-groups', to: 'forms#input_groups', as: :forms_input_groups
    get 'forms/layouts', to: 'forms#layouts', as: :forms_layouts
    get 'forms/pickers', to: 'forms#pickers', as: :forms_pickers
    get 'forms/selects', to: 'forms#selects', as: :forms_selects
    get 'forms/sliders', to: 'forms#sliders', as: :forms_sliders
    get 'forms/switchers', to: 'forms#switchers', as: :forms_switchers
    get 'forms/typeahead', to: 'forms#typeahead', as: :forms_typeahead
    get 'forms/validation', to: 'forms#validation', as: :forms_validation
    get 'forms/wizard', to: 'forms#wizard', as: :forms_wizard
    get 'icons/font-awesome', to: 'icons#font_awesome', as: :icons_font_awesome
    get 'icons/ionicons', to: 'icons#ionicons', as: :icons_ionicons
    get 'icons/linearicons', to: 'icons#linearicons', as: :icons_linearicons
    get 'icons/openiconic', to: 'icons#openiconic', as: :icons_openiconic
    get 'icons/stroke7', to: 'icons#stroke7', as: :icons_stroke7
    get 'dashboards/dashboard-1', to: 'dashboards#dashboard_1', as: :dashboards_dashboard_1
    get 'layout-examples/blank', to: 'layout_examples#blank', as: :layout_examples_blank
    get 'layout-examples/helpers', to: 'layout_examples#helpers', as: :layout_examples_helpers
    get 'layout-examples/horizontal-sidenav', to: 'layout_examples#horizontal_sidenav', as: :layout_examples_horizontal_sidenav
    get 'layout-examples/layout-1-flex', to: 'layout_examples#layout_1_flex', as: :layout_examples_layout_1_flex
    get 'layout-examples/layout-1', to: 'layout_examples#layout_1', as: :layout_examples_layout_1
    get 'layout-examples/layout-2-flex', to: 'layout_examples#layout_2_flex', as: :layout_examples_layout_2_flex
    get 'layout-examples/layout-2', to: 'layout_examples#layout_2', as: :layout_examples_layout_2
    get 'layout-examples/options', to: 'layout_examples#options', as: :layout_examples_options
    get 'layout-examples/without-navbar-flex', to: 'layout_examples#without_navbar_flex', as: :layout_examples_without_navbar_flex
    get 'layout-examples/without-navbar', to: 'layout_examples#without_navbar', as: :layout_examples_without_navbar
    get 'layout-examples/without-sidenav', to: 'layout_examples#without_sidenav', as: :layout_examples_without_sidenav
    get 'misc/blockui', to: 'misc#blockui', as: :misc_blockui
    get 'misc/clipboardjs', to: 'misc#clipboardjs', as: :misc_clipboardjs
    get 'misc/idle-timer', to: 'misc#idle_timer', as: :misc_idle_timer
    get 'misc/ladda', to: 'misc#ladda', as: :misc_ladda
    get 'misc/masonry', to: 'misc#masonry', as: :misc_masonry
    get 'misc/numeraljs', to: 'misc#numeraljs', as: :misc_numeraljs
    get 'misc/perfect-scrollbar', to: 'misc#perfect_scrollbar', as: :misc_perfect_scrollbar
    get 'misc/spinkit', to: 'misc#spinkit', as: :misc_spinkit
    get 'misc/vegasjs', to: 'misc#vegasjs', as: :misc_vegasjs
    get 'pages/account-settings', to: 'pages#account_settings', as: :pages_account_settings
    get 'pages/articles/edit', to: 'pages/articles#edit', as: :pages_articles_edit
    get 'pages/articles/list', to: 'pages/articles#list', as: :pages_articles_list
    get 'pages/authentication/email-confirm', to: 'pages/authentication#email_confirm', as: :pages_authentication_email_confirm
    get 'pages/authentication/lock-screen-v1', to: 'pages/authentication#lock_screen_v1', as: :pages_authentication_lock_screen_v1
    get 'pages/authentication/lock-screen-v2', to: 'pages/authentication#lock_screen_v2', as: :pages_authentication_lock_screen_v2
    get 'pages/authentication/login-and-register', to: 'pages/authentication#login_and_register', as: :pages_authentication_login_and_register
    get 'pages/authentication/login-v1', to: 'pages/authentication#login_v1', as: :pages_authentication_login_v1
    get 'pages/authentication/login-v2', to: 'pages/authentication#login_v2', as: :pages_authentication_login_v2
    get 'pages/authentication/login-v3', to: 'pages/authentication#login_v3', as: :pages_authentication_login_v3
    get 'pages/authentication/password-reset', to: 'pages/authentication#password_reset', as: :pages_authentication_password_reset
    get 'pages/authentication/register-v1', to: 'pages/authentication#register_v1', as: :pages_authentication_register_v1
    get 'pages/authentication/register-v2', to: 'pages/authentication#register_v2', as: :pages_authentication_register_v2
    get 'pages/authentication/register-v3', to: 'pages/authentication#register_v3', as: :pages_authentication_register_v3
    get 'pages/chat', to: 'pages#chat', as: :pages_chat
    get 'pages/clients', to: 'pages#clients', as: :pages_clients
    get 'pages/contacts', to: 'pages#contacts', as: :pages_contacts
    get 'pages/e-commerce/order-detail', to: 'pages/e_commerce#order_detail', as: :pages_e_commerce_order_detail
    get 'pages/e-commerce/order-list', to: 'pages/e_commerce#order_list', as: :pages_e_commerce_order_list
    get 'pages/e-commerce/product-edit', to: 'pages/e_commerce#product_edit', as: :pages_e_commerce_product_edit
    get 'pages/e-commerce/product-item', to: 'pages/e_commerce#product_item', as: :pages_e_commerce_product_item
    get 'pages/e-commerce/product-list', to: 'pages/e_commerce#product_list', as: :pages_e_commerce_product_list
    get 'pages/education/courses-v1', to: 'pages/education#courses_v1', as: :pages_education_courses_v1
    get 'pages/education/courses-v2', to: 'pages/education#courses_v2', as: :pages_education_courses_v2
    get 'pages/faq', to: 'pages#faq', as: :pages_faq
    get 'pages/file-manager', to: 'pages#file_manager', as: :pages_file_manager
    get 'pages/forums/discussion', to: 'pages/forums#discussion', as: :pages_forums_discussion
    get 'pages/forums/list', to: 'pages/forums#list', as: :pages_forums_list
    get 'pages/forums/threads', to: 'pages/forums#threads', as: :pages_forums_threads
    get 'pages/gallery', to: 'pages#gallery', as: :pages_gallery
    get 'pages/help-center', to: 'pages#help_center', as: :pages_help_center
    get 'pages/invoice-print', to: 'pages#invoice_print', as: :pages_invoice_print
    get 'pages/invoice', to: 'pages#invoice', as: :pages_invoice
    get 'pages/kanban-board', to: 'pages#kanban_board', as: :pages_kanban_board
    get 'pages/messages-v1/compose', to: 'pages/messages_v1#compose', as: :pages_messages_v1_compose
    get 'pages/messages-v1/item', to: 'pages/messages_v1#item', as: :pages_messages_v1_item
    get 'pages/messages-v1/list', to: 'pages/messages_v1#list', as: :pages_messages_v1_list
    get 'pages/messages-v2/compose', to: 'pages/messages_v2#compose', as: :pages_messages_v2_compose
    get 'pages/messages-v2/item', to: 'pages/messages_v2#item', as: :pages_messages_v2_item
    get 'pages/messages-v2/list', to: 'pages/messages_v2#list', as: :pages_messages_v2_list
    get 'pages/messages-v3/compose', to: 'pages/messages_v3#compose', as: :pages_messages_v3_compose
    get 'pages/messages-v3/item', to: 'pages/messages_v3#item', as: :pages_messages_v3_item
    get 'pages/messages-v3/list', to: 'pages/messages_v3#list', as: :pages_messages_v3_list
    get 'pages/pricing', to: 'pages#pricing', as: :pages_pricing
    get 'pages/profile-v1', to: 'pages#profile_v1', as: :pages_profile_v1
    get 'pages/profile-v2', to: 'pages#profile_v2', as: :pages_profile_v2
    get 'pages/projects/item', to: 'pages/projects#item', as: :pages_projects_item
    get 'pages/projects/list', to: 'pages/projects#list', as: :pages_projects_list
    get 'pages/search-results', to: 'pages#search_results', as: :pages_search_results
    get 'pages/task-list', to: 'pages#task_list', as: :pages_task_list
    get 'pages/teams', to: 'pages#teams', as: :pages_teams

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :bigint(8)        not null, primary key
#  slug       :string(11)       not null
#  name       :string(100)      not null
#  code       :string(5)        not null
#  client_id  :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Project < ApplicationRecord
  validates :name, presence: true, length: { maximum: 100 }
  validates :code, presence: true, length: { maximum: 5 }, uniqueness: { case_sensitive: false }

  has_many :engagements, dependent: :destroy
  belongs_to :client

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      full_code
    ]
  end

  def self.active
    self.count
  end

  def full_code
    client.code + '-' + code
  end

  def uppercase_code
    code.upcase!
  end

  def to_s
    name
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.friendly.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = 'Project added successfully'
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
    @project = Project.friendly.find(params[:id])
  end

  def update
    @project = Project.friendly.find(params[:id])
    @project.slug = nil
    if @project.update(project_params)
      flash[:success] = 'Project updated'
      redirect_to @project
    else
      render 'edit'
    end
  end

  def project_params
    params.require(:project).permit(:name, :code, :client_id)
  end
end

app/controllers/wrap/pages/projects_controller.rb
module Wrap
  module Pages
    class ProjectsController < WrapController
      def item
        @title = 'Project item - Pages'
      end

      def list
        @title = 'Project list - Pages'
      end
    end
  end
end

app/views/projects/edit.html.erb
<% provide(:title, 'New Project') %>
<h4 class="d-flex flex-wrap justify-content-between align-items-center font-weight-bold pt-2 mb-4">
  <ol class="breadcrumb font-weight-bold m-0">
    <li class="breadcrumb-item"><%= link_to 'Projects', projects_path %></li>
    <li class="breadcrumb-item active"><small>New Project</small></li>
  </ol>
</h4>

<%= form_for @project do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="card mb-4">
    <h6 class="card-header">
      Basic Information
    </h6>
    <div class="card-body">
      <div class="form-group row">
        <%= f.label :name, class: 'col-form-label col-sm-2 text-sm-right' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name'  %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :code, class: 'col-form-label col-sm-2 text-sm-right' %>
        <div class="col-sm-10">
          <%= f.text_field :code, class: 'form-control', placeholder: 'Code'  %>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-4">
    <h6 class="card-header">
      Client
    </h6>
    <div class="card-body">
      <div class="form-group row">
        <%= f.label :client_id, class: 'col-form-label col-sm-2 text-sm-right' %>
        <div class="col-sm-10">
          <%= f.collection_select :client_id, Client.order(:code), :id, :code_and_name_display, { include_blank: false }, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 ml-sm-auto">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', project_path(@project), class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/projects/index.html.erb
<% provide(:title, 'All Projects') %>
<h4 class="d-flex flex-wrap justify-content-between align-items-center font-weight-bold pt-2 mb-4">
  <div class="mb-2">
    <ol class="breadcrumb font-weight-bold m-0">
      <li class="breadcrumb-item"><%= link_to 'Projects', projects_path %></li>
      <li class="breadcrumb-item active"><small>All Projects</small></li>
    </ol>
  </div>
  <div class="mb-2" style="max-width: 200px;">
    <%= link_to new_project_path, class: "btn btn-primary" do %>
      <span class="ion ion-md-add-circle"></span>&nbsp;&nbsp;New Project
    <% end %>
  </div>
</h4>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Code</th>
    <th>Client</th>
    <th>Project Name</th>
    <th>Engagements</th>
  </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <th scope="row"><%= link_to project.full_code, project_path(project) %></th>
      <th scope="row"><%= link_to project.client.name, client_path(project.client) %></th>
      <td><%= project.name %></td>
      <td><%= project.engagements.count %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h4 class="d-flex flex-wrap justify-content-between align-items-center font-weight-bold pt-2 mb-4">
  <ol class="breadcrumb font-weight-bold m-0">
    <li class="breadcrumb-item"><%= link_to 'Projects', projects_path %></li>
    <li class="breadcrumb-item active"><small>New Project</small></li>
  </ol>
</h4>

<%= form_for @project do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="card mb-4">
    <h6 class="card-header">
      Basic Information
    </h6>
    <div class="card-body">
      <div class="form-group row">
        <%= f.label :name, class: 'col-form-label col-sm-2 text-sm-right' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name'  %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :code, class: 'col-form-label col-sm-2 text-sm-right' %>
        <div class="col-sm-10">
          <%= f.text_field :code, class: 'form-control', placeholder: 'Code'  %>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-4">
    <h6 class="card-header">
      Client
    </h6>
    <div class="card-body">
      <div class="form-group row">
        <%= f.label :client_id, class: 'col-form-label col-sm-2 text-sm-right' %>
        <div class="col-sm-10">
          <%= f.collection_select :client_id, Client.order(:code), :id, :code_and_name_display, { include_blank: false }, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 ml-sm-auto">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', projects_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/projects/show.html.erb
<% provide(:title, "#{@project.client.name} - #{@project.name}") %>
<% content_for :styles do %>
  <!-- Page -->
  <%= stylesheet_link_tag 'pages/projects.css', media: 'all' %>
<% end %>

<% content_for :scripts do %>

  <%= javascript_include_tag 'pages_projects_item.js' %>
<% end %>

<!--
=================================================================
**************************** CONTENT ****************************
-->

<h4 class="d-flex flex-wrap justify-content-between align-items-center font-weight-bold pt-2 mb-4">
  <div class="mb-2">
    <ol class="breadcrumb font-weight-bold m-0">
      <li class="breadcrumb-item"><%= link_to 'Projects', projects_path %></li>
      <li class="breadcrumb-item active"><small><%= "#{@project.client.name} - #{@project.name}" %></small></li>
    </ol>
  </div>
  <div class="mb-2" style="max-width: 200px;">
    <%= link_to edit_project_path(@project), class: "btn btn-primary" do %>
      <span class="ion ion-md-arrow-round-forward"></span>&nbsp;&nbsp;Edit Project
    <% end %>
  </div>
</h4>

<div class="row">
  <div class="col">
    <!-- Tabs -->
    <div class="nav-tabs-top mb-4">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#project-engagements">Engagements</a>
        </li>
      </ul>
      <div class="tab-content">

        <!-- Tasks -->
        <div class="tab-pane fade active show" id="project-engagements">

          <div class="card-body">
            <table class="table table-striped">
              <thead>
              <tr>
                <th>Code</th>
                <th>Project Name</th>
                <th>Role</th>
              </tr>
              </thead>
              <tbody>
                <% @project.engagements.each do |engagement| %>
                <tr>
                  <th scope="row"><%= engagement.code %></th>
                  <td><%= engagement.name %></td>
                  <td><%= link_to engagement.role.name, engagement.role %></td>
                  <td><%= engagement.start_date.strftime("%d/%m/%Y") %></td>
                  <td><%= engagement.end_date.strftime("%d/%m/%Y") %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <!-- / Tasks -->
      </div>
    </div>
    <!-- / Tabs -->
  </div>
  <div class="col-md-4 col-xl-3">
    <!-- Project details -->
    <div class="card mb-4">
      <h6 class="card-header">Project details</h6>
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Client</div>
          <div><%= link_to @project.client.name, client_path(@project.client) %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Name</div>
          <div><%= @project.name %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Code</div>
          <div><%= @project.full_code %></div>
        </li>
      </ul>
    </div>
    <!-- / Project details -->

  </div>
</div>